### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by glennovische** [aborn/nuxt-openid-connect#19]
Any plans on adding refresh tokens in the future? By default my provider setting is set to 10 min. Would be great to get a refresh token so the user doenst have to login every 10 min

**Comment by vitjaz** [comment]
The same, I think. Silent renew token really need...

**Comment by aborn** [comment]
Thanks advice,  the latest version (v0.6.0) finished the feature. You can try it and give me feedback. Thanks a lot!
