### ISSUE TITLE
Error accessing access_token in callback

### ISSUE THREAD

**Issue by painerp** [aborn/nuxt-openid-connect#22]
Hi,

Thanks for the great tool! I attempted to use it with the latest version of Nuxt (3.6.1) and integrated Authentik as the OIDC provider. However, I encountered some issues during the process.

Here's the problematic output I received when I enabled debugging:

```
[CALLBACK]: has access_token in params, accessToken:eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc2Y2FlZThhMjIxNTVm...
[CALLBACK]: TypeError: Cannot read properties of null (reading 'access_token')
```

In my understanding, it seems like this issue arose when the support for refresh_token was added, although I'm not entirely certain. The problem appears to be that `tokenSet` is set to null in [`callback.ts`](https://github.com/aborn/nuxt-openid-connect/blob/a3f20999b1a2e3f7c3670451a3cbde30a7b22ff5/src/runtime/server/routes/oidc/callback.ts#L42), yet `setCookieTokenAndRefreshToken` still attempts to access the `access_token` without taking this into consideration. The error occurs at the following line: [link to the problematic line](https://github.com/aborn/nuxt-openid-connect/blob/a3f20999b1a2e3f7c3670451a3cbde30a7b22ff5/src/runtime/utils/utils.ts#L13).

Thank you for taking the time to look into this matter.

**Comment by rkorzhoff** [comment]
@aborn can you release this fix please?

**Comment by aborn** [comment]
> @aborn can you release this fix please?

done, version 0.6.2
